theme: jekyll-theme-slate
title: Development Portfolio
description: Test Automation and Development Portfolio
plugins:
  - jekyll-paginate
paginate: 5
collections:
  pages:
    output: true
    permalink: /:path/